#!/usr/bin/python3

import glob

res = []

for i in glob.glob("config/*.list"):
    print("#", "reading from", i)
    for j in open(i, encoding="utf-8").read().split("\n"):
        val = j.split('#', 1)[0].strip()
        if val != "":
        	res.extend(val.split(" "))


"""
print("#", "final result:")
for x in res:
	print("#", "'%s'" % x)
"""


	
# For hosts
s = """# This file is auto generated by `expt.py` in https://github.com/zcmimi/hosts-for-working-hard.
# Any changes applied will be removed after next generating.

"""
for x in res:
	s += "%s 114.215.147.61\n" % x
open("hosts", "w", encoding="utf-8").write(s)

# For m
